function(qd3_read_autotools_version out_var)
  file(READ "${CMAKE_SOURCE_DIR}/configure.ac" configure_ac)
  string(REGEX MATCH "define\\(\\[QD_PATCH_VERSION\\], *([0-9]+)\\)" patch_match "${configure_ac}")
  if(NOT patch_match)
    message(FATAL_ERROR "Could not parse QD_PATCH_VERSION from configure.ac")
  endif()
  set(patch "${CMAKE_MATCH_1}")
  string(REGEX MATCH "AC_INIT\\(\\[qd3\\],\\[([0-9]+)\\.([0-9]+)\\.QD_PATCH_VERSION\\]" init_match "${configure_ac}")
  if(NOT init_match)
    message(FATAL_ERROR "Could not parse AC_INIT qd3 version from configure.ac")
  endif()
  set(${out_var} "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${patch}" PARENT_SCOPE)
endfunction()

function(qd3_assert_version_sync)
  qd3_read_autotools_version(autotools_version)
  if(NOT autotools_version STREQUAL PROJECT_VERSION)
    message(FATAL_ERROR "Version mismatch: configure.ac=${autotools_version}, CMakeLists.txt=${PROJECT_VERSION}")
  endif()
endfunction()
